### ISSUE TITLE
Initial functionality

### ISSUE THREAD

**Issue by docktermj** [senzing-garage/sz-sdk-python#3]
### Tasks

- [ ] Automation
  - [ ] Code quality testing
    - [x] Flake8 - Code style enforcement
    - [x] pylint - Static code analysis
    - [x] isort - Import management
    - [x] Black - Code formatter
    - [x] Mypy - Static type checker
    - [ ] Ruff - linting/formatting
  - [x] Unit testing
    - [x] pytest
  - [x] Code coverage
    - [x] pytest-cov
    - [x] Coverage gutters in VSCode - [setup](https://dev.to/yamakanto/how-i-set-up-vscode-for-python-tests-coverage-profiling-2jf4)
  - [x] Documentation creation
    - [x] Sphinx
    - [x] mkdocs
- [x] Development environment
  - [x] VSCode extensions
    - [x] Pylance
    - [x] Python
    - [x] Python Indent
    - [x] autoDocstring
    - [x] Black Formatter
    - [x] Flake8
    - [x] isort
    - [x] Coverage gutters 
  - [x] Support development on Linux, Darwin, and Windows
    - [x] Makefile
- [x] Design
  - [x] Abstractions
  - [x] Constructor / Destructor
  - [x] Code comment style for generated documentation
  - [x] Python/C binding
  - [x] Exception management
- [ ] Code
  - [x] Create abstract classes
  - [x] Define C API in Python (`.argtypes` and `.restype`)
  - [ ] Create reusable Exceptions
  - [ ] Implement class methods
  - [x] Use of `Error` suffix for Exceptions
- [ ] Test
  - [ ] Unit test cases
  - [ ] Test fixtures (TruthSet data, reusable Records)
- [ ] Documentation
  - [ ] Method documentation
  - [ ] Code examples
  - [ ] List Exceptions returned

###  Open items

- [x] Separating examples in the documentation
- [ ] Finding `.so` and `.dll` files (i.e. replace `find_file_in_path()`)
- [ ] Consider [g2_flags.py](https://github.com/Senzing/g2-sdk-python-grpc/blob/issue-3.gadair.2/src/client/g2_flags.py) approach to setting flags
- [ ] Look into replacing Flake8 with Ruff now it has black formatting and is very fast
- [x] Use of `assert` in production code (i.e. non-test)
- [x] Potentially wrap `ctypes.ArgumentError` as `TypeError` so user doesn't have to `import ctypes`

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/senzing-garage/sz-sdk-python/pull/4
- https://github.com/senzing-garage/sz-sdk-python/pull/5
- https://github.com/senzing-garage/sz-sdk-python/pull/6
- https://github.com/senzing-garage/sz-sdk-python/pull/9
- https://github.com/senzing-garage/sz-sdk-python/pull/12
- https://github.com/senzing-garage/sz-sdk-python/pull/13
- https://github.com/senzing-garage/sz-sdk-python/pull/14
- https://github.com/senzing-garage/sz-sdk-python/pull/15
- https://github.com/senzing-garage/sz-sdk-python/pull/16
- https://github.com/senzing-garage/sz-sdk-python/pull/19
- https://github.com/senzing-garage/sz-sdk-python/pull/20
- https://github.com/senzing-garage/sz-sdk-python/pull/21
- https://github.com/senzing-garage/sz-sdk-python/pull/22
- https://github.com/senzing-garage/sz-sdk-python/pull/23
- https://github.com/senzing-garage/sz-sdk-python/pull/24
- https://github.com/senzing-garage/sz-sdk-python/pull/25
- https://github.com/senzing-garage/sz-sdk-python/pull/26
- https://github.com/senzing-garage/sz-sdk-python/pull/27
- https://github.com/senzing-garage/sz-sdk-python/pull/28
- https://github.com/senzing-garage/sz-sdk-python/pull/29
- https://github.com/senzing-garage/sz-sdk-python/pull/35
- https://github.com/senzing-garage/sz-sdk-python/pull/55
- https://github.com/senzing-garage/sz-sdk-python/pull/62
- https://github.com/senzing-garage/sz-sdk-python/pull/66
- https://github.com/senzing-garage/sz-sdk-python/pull/68
- https://github.com/senzing-garage/sz-sdk-python/pull/69
